# Generated by Django 3.2.8 on 2022-02-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20220215_1945'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productreview'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
