# Generated by Django 3.2.10 on 2022-02-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220224_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
