# Generated by Django 3.2.10 on 2022-02-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220224_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reff',
            field=models.SlugField(default='', max_length=255),
        ),
    ]
