# Generated by Django 3.2.7 on 2021-09-25 02:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Kamu : ')),
                ('desc', ckeditor.fields.RichTextField()),
                ('profile_img', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
