# Generated by Django 3.2.7 on 2021-09-25 03:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(max_length=255, verbose_name='Social Media Name : ')),
                ('icon', models.CharField(max_length=255, verbose_name='Icon Class')),
                ('redirect', models.CharField(max_length=255, verbose_name='Link Social Media Kamu')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='Deskripsi Singkat : '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(upload_to='profile', verbose_name='Foto Profil : '),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul Posting : ')),
                ('link', models.SlugField(max_length=255)),
                ('content', ckeditor.fields.RichTextField(verbose_name='Konten')),
                ('desc', models.TextField()),
                ('keyword', models.TextField()),
                ('social_media', models.ManyToManyField(to='backend.SocialMedia')),
            ],
        ),
    ]
