# Generated by Django 3.2.7 on 2021-09-25 07:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210925_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='social_media',
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media',
            field=models.ManyToManyField(to='backend.SocialMedia'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Konten '),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(verbose_name='Deskripsi Singkat '),
        ),
        migrations.AlterField(
            model_name='post',
            name='keyword',
            field=models.TextField(verbose_name='keyword pencarian '),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Judul Posting  '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='Deskripsi Singkat  '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama Kamu  '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(upload_to='profile', verbose_name='Foto Profil '),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(max_length=255, verbose_name='Icon Class '),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='redirect',
            field=models.CharField(max_length=255, verbose_name='Link Social Media Kamu '),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social',
            field=models.CharField(max_length=255, verbose_name='Social Media Name '),
        ),
    ]
