# Generated by Django 3.2.7 on 2021-09-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210925_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='backend.SocialMedia'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ico', to='backend.mediaicon'),
        ),
    ]
