# Generated by Django 3.2.7 on 2021-09-26 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_mediamanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_create',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date_update',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
