# Generated by Django 3.2.7 on 2021-09-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210926_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nick_name',
            field=models.CharField(default='Annisa Maharani', max_length=255, verbose_name='Nama Panggilan'),
        ),
    ]
