# Generated by Django 3.2.7 on 2021-10-12 12:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=255, verbose_name='Nama Produk')),
                ('p_link', models.SlugField(max_length=255, unique=True)),
                ('p_content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('p_desc', models.TextField(verbose_name='Simple Description')),
                ('p_keyword', models.TextField(verbose_name='keyword')),
                ('p_date_create', models.DateField(auto_now=True)),
                ('p_date_update', models.DateField(auto_now_add=True)),
                ('p_likes', models.IntegerField(default=0, verbose_name='likes')),
            ],
        ),
    ]
