# Generated by Django 3.2.7 on 2021-10-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20211013_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='p_img',
            field=models.CharField(default=255, max_length=255, verbose_name='Link Gambar Produk'),
        ),
    ]
