# Generated by Django 3.2.8 on 2022-02-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_productreview_p_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Harga yang akan di jual : '),
        ),
        migrations.AddField(
            model_name='productreview',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='price',
            field=models.FloatField(default=0, verbose_name='Harga asli produk : '),
            preserve_default=False,
        ),
    ]
