# Generated by Django 3.2.8 on 2022-02-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20220215_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='p_img',
            field=models.FileField(default='', max_length=255, upload_to='product/img/', verbose_name='Link Gambar Produk'),
        ),
    ]
