# Generated by Django 3.2.10 on 2022-02-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='', max_length=255, verbose_name='Nomor Telepon : '),
        ),
    ]
